name: make lint
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
    matrix:
      node-version: [10.x, 12.x, 14.x, 15.x, 16.x, 17.x]

    steps:
      - name: eslintStart
        run: make lint
